# This is a basic workflow to help you get started with Actions

name: "Build Pull Request"

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: 
      - master
    types:
      - opened
      - reopened
      - edited
      - synchronize
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  install:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Bootstrap Lerna
        run: npm run bootstrap
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Run after
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Bootstrap Lerna
        run: npm run bootstrap
      - name: Lint Source
        run: npm run lint
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Run after
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Bootstrap Lerna
        run: npm run bootstrap
      - name: Build Packages
        run: npm run build
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Run after
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Bootstrap Lerna
        run: npm run bootstrap
      - name: Run unit tests
        run: npm run test
